spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zzx0-0/config-repo.git
          username: zzx0-0
          password: 5ay3mk9Q
          #basedir: /fileRoot/config/baseDi     #配置存储目录
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"

##  curl -v -X POST "http://localhost:8080/actuator/bus-refresh"